# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-yaml
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args: [--config=.flake8]
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
        files: '^frontend/.*'
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.33.0
    hooks:
      - id: eslint
        additional_dependencies:
          - babel-preset-react-app@10.0.1
          - eslint@8.33.0
          - eslint-config-airbnb@19.0.4
          - eslint-config-prettier@8.6.0
          - eslint-config-react-app@7.0.1
          - eslint-import-resolver-webpack@0.13.2
          - eslint-plugin-import@2.27.5
          - eslint-plugin-jsx-a11y@6.7.1
          - eslint-plugin-react@7.32.2
          - eslint-plugin-react-hooks@4.6.0
        types: [file]
        types_or: [javascript, jsx]
        verbose: true
        args:
          [
            "--rule",
            "import/no-unresolved: 0",
            "--fix",
          ]

default_language_version:
  node: "18.12.1"
